### ISSUE TITLE
Leaking sensitive information via file

### ISSUE THREAD

**Issue by CristiVlad25** [mozilla-it/air.mozilla.org#47]
Hello, you're leaking private keys via this file:

https://github.com/mozilla-it/air.mozilla.org/blob/master/nubis/puppet/files/settings.py

If that's unintentional, make sure to set appropriate access controls so that your keys are not abused by unauthorized parties.

Regards

**Comment by gozer** [comment]
There are old / not used anymore, but thanks for the spot. I'll be removing them to avoid confusion in the future.
